coverage:
  status:
    project:
      default:
        target: 10%
    patch:
      default:
        target: 10%

comment:
  layout: " diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false
